### ISSUE TITLE
LinearVelocity no longer a Velocity

### ISSUE THREAD

**Issue by fkleedorfer** [qudtlib/qudtlib-java#61]
Since the last release, the LinearVelocity and some other quantity kinds are no longer connected to their more general quantity kinds in the hierarchy and their applicable units are gone.

The reason is that they are now associated via 'qudt:exactMatch' (and owl:sameAs) in QUDT, which is not honored by QUDTLib.

**Comment by steveraysteveray** [comment]
This is not good. The reason we made that change is because we are now enforcing the constraint that quantity kinds related by skos:broader must have the same dimension vector. This allows proper functioning of the calculation of applicable units. Previously, we allowed a more liberal interpretation of skos:broader, but that gets us into trouble with applicable units.

What to do? Is it not practical to adjust your scripts that build QUDTLib? How do you imagine the use of skos:broader in your use cases?

**Comment by fkleedorfer** [comment]
Thanks for clarifying, @steveraysteveray! This issue was not meant as a criticism of QUDT but as a problem description that can be referenced in the upcoming PR to QUDTLib. It's clearly a bug on our side - we have to keep up with the changes in QUDT and we missed this one. 

My first approach is to pull specific properties into the quantitykinds that are linked via owl:sameAs, represent the `exactMatch` links explicitly in the domain model, and use the exactMatch links when needed in the relevant algorithms. 

If that turns out to be too cumbersome, I might end up performing owl:sameAs reasoning on the quantitykind vocabulary (maybe also the unit one) before populating the model, but I am a bit daunted because it will generate many new triples and there is some chance to introduce bugs inadvertedly.

**Comment by steveraysteveray** [comment]
@fkleedorfer, please be aware that we have retired the use of owl:sameAs in the vocabularies, partly because of the many new triples that result with OWL reasoning ([see Release notes here](https://github.com/qudt/qudt-public-repo/releases/tag/v2.1.31)). (A few owl:sameAs triples reappeared recently after a merge where I didn't notice them slipping back in, but that will be fixed in PR #799). We use the qudt:exactMatch relation where needed. So your last option won't be an option.

**Comment by fkleedorfer** [comment]
Ok thanks! Approach 1 seems to work nicely.
